#!/bin/bash

file=$(sed -n -e 's/^.*PROG_NAME  = //p' Makefile)
file="./bin/$file"

if [ -e "$file" ]; then
	./$file	
else 
	echo -e "\033[1;31mProgram nie jest jeszcze skompilowany! Uruchom: 'make'!\033[0m"
fi 
